server:
  port: 8082
  servlet-path: "/"
  display-name: "SebArmBack"
  ssl.enabled: false
#security:
#  basic.enabled: false
#  user.name: root
#  user.password: root


awesome.security.jwt:
    tokenExpirationTime: 15 # Number of Hours
    refreshTokenExpTime: 60 # Number of Hours
    tokenIssuer: http://socialWar.kth
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    claimKeyIssuer: issuer
    claimKeySubject: sub
    claimKeyAudience: audience
    claimKeyCreated: created
    claimKeyPayload: payload
    claimKeyRoles: roles
    audienceUnknown: unknown
    audienceWeb: web
    audienceMobile: mobile
    audienceTablet: tablet
    creationBufferSeconds: 600 #6 min

awesome.security.key:
    sharedSecretKey: NMg+3ftaYoaqh9uCMN8gbD2xgWkaq6SkiDpjcTuMnQY=
    serverRsaPrivateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKocQGxL1Z5n6GLEYTkMd5SUKuP5FbmdZMZrlz0CHbHu4dKcQXF8xlaQHWyblf8UfEnr6QMuLbK1UaHql5zm1IpibToiT4MSH1GARZtslbmZ5NaWmQkkg0uUbK0uq5CUX8lwWwW0NFmUoTFtXRkaVTtwJ2HXHHLV86P8h2Qvv2K/AgMBAAECgYB8HkT7P5HMFLDAb90oTOprZHivAi1R03+WLyaYgxS7oTrv+sbdUVc+DcUKW7Nj/MR7A0Bu66C4RggcBhk9iEcGxsupUv5N6jG9CvXhwHjkNtQaVuuMkNNqpB0wYdm5BWgtP3d/J9u0z3HZIOTOKp1KgV0SgeDdBhQAGwOtpAa4gQJBAOxQSk0JGr7/eCZlR3rA2CGD8PP9FNbsSq/vO/qbXRh6OBoJtZ4um0u7YKXtCdavoQmhRyJzQ8HZqmGJeR2D8mECQQC4SBYj48ctfX+0w+rvxbcwUSExuRzp6oBoakYGr3ISlZo0Z1sTO+LofGkAEZ2pzA7AuV8TxCPUssGJaWTuo6kfAkEArBggtA9QUg4cAuI49vVfsLC0lgsV1RsJnSx9IploZ74CAzxU7liEsddIoC2Kv7TxcuDnu/fzPUX15chG0q7XoQJBAI/KZ8QvWl4re7dP3ASlcNA5rb3/pAj9mp5eti9HPKo1o3JaZ101sFMZqFCObkhsWeKVghOJSzAPHyaaX1A50Z8CQQCWM9ftCtCz6TZYrqjFlZr/Bl3EW+JKloir2ZjzaSAwqogcQONl30ZflIM9X3x5ACX2likT8BiBtCVh/NHF3ej+
    serverRsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqHEBsS9WeZ+hixGE5DHeUlCrj+RW5nWTGa5c9Ah2x7uHSnEFxfMZWkB1sm5X/FHxJ6+kDLi2ytVGh6pec5tSKYm06Ik+DEh9RgEWbbJW5meTWlpkJJINLlGytLquQlF/JcFsFtDRZlKExbV0ZGlU7cCdh1xxy1fOj/IdkL79ivwIDAQAB
    encryptPayloadKey: 8j/2Bs9KyUYnLYsjGkWspA==
# Log Level — ERROR, WARN, INFO, DEBUG or TRACE.

logging:
#    file: Captains.log
    level:
          org:
              hibernate: INFO
              springframework.web: INFO
    level.: INFO

spring:
  profiles:
    include: @activatedProperties@
    active: @activatedProperties@

---
# ###########################################################
# H2 Database
# ###########################################################
spring:
  profiles: h2Development
  http:
      encoding.charset: UTF-8
      multipart.max-request-size: 10MB
  data.jpa.repositories.enabled: true
  datasource:
      platform: H2
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa
#      data: classpath*:data.sql
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
        naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #none, validate, update, create, create-drop
        ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties.hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  activemq:
    pool:
      max-connections: 10


---
# ###########################################################
# MySQL
# ###########################################################
spring:
  profiles: mysqlProduction
  http:
      encoding.charset: UTF-8
      multipart.max-request-size: 10MB
  data.jpa.repositories.enabled: true
  datasource:
      platform: MYSQL
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=false&useSSL=false&requireSSL=false
      username: root
      password: root

#      data: classpath*:data.sql
  jpa:
      open-in-view: false
      generate-ddl: true
      hibernate:
          naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          #none, validate, update, create, create-drop
          ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: false
      properties.hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          database: MYSQL
          show-sql: true

  h2:
    console:
      enabled: false
      path: /console
      settings:
        web-allow-others: true
  activemq:
    pool:
      max-connections: 10



